services:
  blog-backend:
    container_name: blog_backend
    build:
      context: ./Backend
      dockerfile: Blog.Web/Dockerfile.dev
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    networks:
      - blog-network
    volumes:
      - ./Backend:/src
      - nuget_cache:/root/.nuget/packages
    working_dir: /src/Blog.Web
    command: >
      sh -c "dotnet watch run --urls http://0.0.0.0:5000"

  blog-frontend:
    container_name: blog_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - blog-backend
    env_file:
      - ./Frontend/.env
    networks:
      - blog-network

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: blogger
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "10080:8080"
    depends_on:
      - db
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
  nuget_cache:
