services:
  blog-backend:
    container_name: blog_backend
    image: blog-backend
    build:
      context: ./Backend
      dockerfile: Blog.Web/Dockerfile.dev
    env_file:
      - ./Backend/.env
    ports:
      - "6123:6123"
    depends_on:
      - db
    networks:
      - blog-network
      
  blog-frontend:
    container_name: blog_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - blog-backend
    env_file:
      - ./Frontend/.env
    networks:
      - blog-network

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_DB: dbname
      POSTGRES_PASSWORD: dbpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  db_data:
  frontend_node_modules:
