services:
  blog-backend:
    image: ghcr.io/xirzo/blog-backend:0.0.7
    secrets:
      - jwt_key
      - jwt_issuer
      - jwt_audience
    ports:
      - "6123:6123"
    environment:
      JWT_KEY: /run/secrets/jwt_key
      JWT_ISSUER: /run/secrets/jwt_issuer
      JWT_AUDIENCE: /run/secrets/jwt_audience
    depends_on:
      - db
    networks:
      - blog-network
    deploy:
      restart_policy:
        condition: on-failure
      
  blog-frontend:
    image: ghcr.io/xirzo/blog-frontend:0.0.2
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=http://localhost:5000
      - VITE_LOGO_TEXT=Xirzo Blog
    depends_on:
      - blog-backend
    networks:
      - blog-network
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_DB: dbname
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

networks:
  blog-network:
    driver: overlay

volumes:
  postgres_data:

secrets:
  jwt_key:
    external: true
  jwt_issuer:
    external: true
  jwt_audience:
    external: true
