services:
  blog-backend:
    image: ghcr.io/xirzo/blog-backend:latest
    secrets:
      - db_connection_string
      - jwt_key
      - jwt_issuer
      - jwt_audience
    ports:
      - "6123:6123"
    environment:
      FRONTEND_ORIGIN: https://xirzo.ru
      DB_CONNECTION_STRING: /run/secrets/db_connection_string
      JWT_KEY: /run/secrets/jwt_key
      JWT_ISSUER: /run/secrets/jwt_issuer 
      JWT_AUDIENCE: /run/secrets/jwt_audience
    depends_on:
      - db
    networks:
      - blog-network
    deploy:
      restart_policy:
        condition: on-failure
      
  blog-frontend:
    image: ghcr.io/xirzo/blog-frontend:latest
    ports:
      - "3000:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=https://api.xirzo.ru
      - VITE_LOGO_TEXT=Xirzo Blog
    depends_on:
      - blog-backend
    networks:
      - blog-network
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432" 
    secrets:
      - dbuser
      - dbname
      - dbpass
    environment:
      POSTGRES_USER_FILE: /run/secrets/dbuser
      POSTGRES_DB_FILE: /run/secrets/dbname
      POSTGRES_PASSWORD_FILE: /run/secrets/dbpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blog-network

networks:
  blog-network:
    driver: overlay

volumes:
  db_data:

secrets:
  db_connection_string:
    external: true
  jwt_key:
    external: true
  jwt_issuer:
    external: true
  jwt_audience:
    external: true
  dbuser:
    external: true
  dbname:
    external: true
  dbpass:
    external: true
