<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.Extensions.Configuration"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Application\Blog.Application.Abstractions\Blog.Application.Abstractions.csproj"/>
    </ItemGroup>

</Project>
